In [1]:
import ser_standardizer as ser

In [2]:
df_all = ser.load_datasets(["crema_d", "ravdess", "iemocap"])

In [3]:
df_all

,dataset,file_path,speaker_id,gender,emotion,sentence_text,language
0,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1001,Male,Anger,Don't forget a jacket.,en
1,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1001,Male,Disgust,Don't forget a jacket.,en
2,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1001,Male,Fear,Don't forget a jacket.,en
3,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1001,Male,Neutral,Don't forget a jacket.,en
4,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1001,Male,Neutral,Don't forget a jacket.,en
...,...,...,...,...,...,...,...
18916,IEMOCAP,C:\Users\Vinicius Suaiden\Downloads\Datasets\I...,iemocap_Ses5_M,Male,Anger,"You are a vile tempered, wicked living, evil l...",en
18917,IEMOCAP,C:\Users\Vinicius Suaiden\Downloads\Datasets\I...,iemocap_Ses5_M,Male,Anger,"Oh, you're not going like this.",en
18918,IEMOCAP,C:\Users\Vinicius Suaiden\Downloads\Datasets\I...,iemocap_Ses5_M,Male,Anger,"[GARBAGE] No, you're not.",en
18919,IEMOCAP,C:\Users\Vinicius Suaiden\Downloads\Datasets\I...,iemocap_Ses5_M,Male,Anger,oh! Marry you again? I wouldn't marry you agai...,en
18920,IEMOCAP,C:\Users\Vinicius Suaiden\Downloads\Datasets\I...,iemocap_Ses5_M,Male,Anger,You're a wicked little vampire. And I pray to...,en

In [4]:
df_filtered = ser.filters(
    df_all,
    datasets='crema-d',
    emotions=['anger', 'happy'], 
    genders=['female'],
)

Filtro aplicado. Restaram 779 amostras.

In [5]:
df_filtered

,dataset,file_path,speaker_id,gender,emotion,sentence_text,language
82,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1002,Female,Anger,Don't forget a jacket.,en
85,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1002,Female,Happy,Don't forget a jacket.,en
89,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1002,Female,Anger,It's eleven o'clock.,en
90,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1002,Female,Anger,It's eleven o'clock.,en
104,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1002,Female,Anger,I'm on my way to the meeting.,en
...,...,...,...,...,...,...,...
7403,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1091,Female,Happy,I would like a new alarm clock.,en
7418,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1091,Female,Anger,The airplane is almost full.,en
7424,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1091,Female,Anger,That is exactly what happened.,en
7430,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1091,Female,Anger,The surface is slick.,en
7436,CREMA-D,C:\Users\Vinicius Suaiden\Downloads\Datasets\D...,crema_1091,Female,Anger,We'll stop in a couple of minutes.,en

In [6]:
features = ser.extract_features(df_filtered, feature_set='eGeMAPS', use_vad=False, sr=16000)

Inicializando openSMILE (eGeMAPS)...

Extraindo características:   0%|          | 0/779 [00:00<?, ?it/s]

Consolidando matriz de features...

In [7]:
features

,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2,F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope,F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope,F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope,F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
82,46.862366,0.031873,45.885506,47.090183,47.503166,1.617661,57.521851,50.485283,63.617313,48.711250,...,0.016607,0.002137,0.134288,2.352941,1.200000,0.286667,0.156276,0.392500,0.321588,-19.355112
85,43.874290,0.061580,40.760582,44.799267,46.513962,5.753380,23.156277,9.049630,-26.560154,43.854259,...,0.015807,0.003162,0.106808,2.283105,2.336449,0.096000,0.031369,0.308000,0.304985,-29.673281
89,44.639236,0.094351,39.311138,47.151501,48.256577,8.945438,50.959000,18.541311,103.352081,86.727699,...,0.020897,0.005290,0.164724,2.092050,1.709402,0.137500,0.064566,0.340000,0.349113,-22.027596
90,42.510792,0.121605,38.882969,40.848503,48.742996,9.860027,86.488914,72.434746,79.090225,112.677536,...,0.019044,0.003173,0.152845,2.545455,1.481481,0.135000,0.113468,0.414000,0.443152,-24.116360
104,42.937481,0.073497,40.528946,43.133221,45.111568,4.582623,159.324738,98.001587,25.736111,5.329165,...,0.016124,0.001067,0.134570,2.482270,1.444043,0.282500,0.270959,0.510000,0.355622,-20.344221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7403,29.964607,0.180377,27.482992,29.959862,31.143471,3.660479,25.369617,13.973416,71.608826,0.000000,...,-0.011560,0.000968,0.071090,2.641510,1.923077,0.132000,0.097036,0.305000,0.313356,-34.943535
7418,39.250851,0.070699,36.421379,39.697369,42.341621,5.920242,17.719833,9.876608,10.770851,36.054676,...,-0.004065,-0.009732,0.119485,2.155173,2.202643,0.128000,0.057411,0.253333,0.306576,-27.237164
7424,36.595932,0.179450,34.809059,38.338806,39.810135,5.001076,21.416426,8.941959,148.282013,121.284302,...,-0.001646,-0.007649,0.171297,3.018868,3.461539,0.082222,0.048483,0.167000,0.218314,-23.221403
7430,40.629562,0.073855,37.315468,42.887272,43.545315,6.229847,33.779770,21.395926,10.970665,14.214913,...,-0.007313,-0.000992,0.111668,2.790698,2.380953,0.088000,0.047917,0.308000,0.298490,-28.830011
7436,29.633892,0.322315,13.398706,33.035599,35.563786,22.165079,148.175964,98.958702,46.173820,25.580414,...,-0.011366,-0.003487,0.075952,3.396227,4.230769,0.082727,0.056904,0.121667,0.143923,-32.111622

In [8]:
import opensmile

for feature_set in opensmile.FeatureSet:
    print(feature_set.name)

ComParE_2016
GeMAPS
GeMAPSv01b
eGeMAPS
eGeMAPSv01b
eGeMAPSv02
emobase
IS09
IS10
IS11
IS12
IS13

(e)GeMAPS: minimalista, dados selecionados teoricamente (menos de 100)
IS e ComParE: Força bruta (milhares)
emobase: intermediário clássico, usado como baseline

smile = opensmile.Smile(
    feature_set = opensmile.FeatureSet.eGeMAPSv02,
    feature_level = opensmile.FeatureLevel.LowLevelDescriptors,
)